CREATE TABLE VEMSER_NOGUEIRA.ESTUDANTE(
	id_estudante NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR,
	PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE VEMSER_NOGUEIRA.SEQ_ESTUDANTE
	START WITH 1
	INCREMENT BY 1
	NOCACHE NOCYCLE;
	
INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Bruno Nogueira', TO_DATE('28-09-1993', 'dd-mm-yyyy'), 0000000001, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Rosângela Pires', TO_DATE('03-04-1963', 'dd-mm-yyyy'), 0000000002, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Diogo Mota', TO_DATE('14-05-1976', 'dd-mm-yyyy'), 0000000003, 'N');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Caio Monteiro', TO_DATE('15-05-1990', 'dd-mm-yyyy'), 0000000004, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Felipe Figueiredo', TO_DATE('16-03-1994', 'dd-mm-yyyy'), 0000000005, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Cecília Duarte', TO_DATE('02-05-1992', 'dd-mm-yyyy'), 0000000006, 'N');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Carlos Moura', TO_DATE('08-08-1998', 'dd-mm-yyyy'), 0000000007, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Mariane Pereira', TO_DATE('18-03-1991', 'dd-mm-yyyy'), 0000000008, 'N');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Marcelo Sales', TO_DATE('27-06-1989', 'dd-mm-yyyy'), 0000000009, 'S');

INSERT INTO VEMSER_NOGUEIRA.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA ,ATIVO)
VALUES (SEQ_ESTUDANTE.nextval, 'Debora Maia', TO_DATE('10-10-1993', 'dd-mm-yyyy'), 0000000010, 'S');

SELECT * FROM VEMSER_NOGUEIRA.ESTUDANTE;
