SELECT p.NOME,c.NUMERO,c.DESCRICAO 
  FROM VEMSER_NOGUEIRA.PESSOA p
  RIGHT JOIN VEMSER_NOGUEIRA.CONTATO c ON (c.ID_PESSOA = p.ID_PESSOA)

SELECT p.NOME,ep.LOGRADOURO,ep.NUMERO 
  FROM VEMSER_NOGUEIRA.PESSOA p 
  RIGHT JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  RIGHT JOIN VEMSER_NOGUEIRA.ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)

SELECT p.NOME,ep.LOGRADOURO,ep.NUMERO 
  FROM VEMSER_NOGUEIRA.PESSOA p 
  RIGHT JOIN VEMSER_NOGUEIRA.CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)
  RIGHT JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  RIGHT JOIN VEMSER_NOGUEIRA.ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)

SELECT p.NOME,c.NUMERO,c.DESCRICAO 
  FROM VEMSER_NOGUEIRA.PESSOA p 
  FULL JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)

SELECT p.NOME,ep.LOGRADOURO,ep.NUMERO 
  FROM VEMSER_NOGUEIRA.PESSOA p 
  FULL JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  FULL JOIN VEMSER_NOGUEIRA.ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)

SELECT p.NOME,ep.LOGRADOURO,ep.NUMERO 
  FROM VEMSER_NOGUEIRA.PESSOA p 
  FULL JOIN VEMSER_NOGUEIRA.CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)
  FULL JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  FULL JOIN VEMSER_NOGUEIRA.ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)
  
SELECT p.NOME, pxpe.ID_ENDERECO  
  FROM VEMSER_NOGUEIRA.PESSOA p 
  INNER JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  WHERE EXISTS (SELECT ep.LOGRADOURO 
                  FROM VEMSER_NOGUEIRA.ENDERECO_PESSOA ep 
				 WHERE ep.ID_ENDERECO = pxpe.ID_ENDERECO AND ep.LOGRADOURO  IS NOT NULL
				)
  
SELECT p.ID_PESSOA ||' - '|| p.NOME ||' - '|| ep.ID_ENDERECO ||' - '|| ep.LOGRADOURO ID_NOME_ID_LOGRADOURO
  FROM VEMSER_NOGUEIRA.PESSOA p 
  INNER JOIN VEMSER_NOGUEIRA.PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
  INNER JOIN VEMSER_NOGUEIRA.ENDERECO_PESSOA ep ON (pxpe.ID_ENDERECO = ep.ID_ENDERECO)