SELECT * 
  FROM VEMSER_NOGUEIRA.PAIS 
  ORDER BY NOME 
  DESC;

SELECT LOGRADOURO, CEP 
  FROM VEMSER_NOGUEIRA.ENDERECO 
  WHERE UPPER(LOGRADOURO) 
  LIKE 'A%';
 
SELECT * 
  FROM ENDERECO 
  WHERE TRIM(CEP) 
  LIKE '%0';
 
SELECT * 
  FROM VEMSER_NOGUEIRA.ENDERECO 
  WHERE NUMERO 
  BETWEEN 1 AND 100;
 
SELECT * 
  FROM VEMSER_NOGUEIRA.ENDERECO 
  WHERE UPPER(LOGRADOURO) 
  LIKE 'RUA%' 
  ORDER BY CEP DESC;

SELECT COUNT(LOGRADOURO) 
  FROM VEMSER_NOGUEIRA.ENDERECO;
 
SELECT ID_CIDADE,COUNT(LOGRADOURO) 
  FROM VEMSER_NOGUEIRA.ENDERECO 
  GROUP BY ID_CIDADE;
